<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReadinessIndicatorsSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('readiness_scores')->truncate();
        DB::table('readiness_indicators')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $indicators = [
            // ── Mobilisation & availability (weight 25) ──────────────────────
            [
                'code' => 'M1',
                'category' => 'Mobilisation & availability',
                'category_weight' => 25,
                'indicator_name' => 'Named operators deployable within 60 minutes inside group footprint',
                'evidence_examples' => 'Duty roster; turnout drill; named contact list; recent mobilisation test',
                'anchor_0' => 'No named local turnout or not tested',
                'anchor_3' => 'Some likely local turnout but inconsistent',
                'anchor_5' => 'Named and evidenced operators available for rapid local deployment',
                'indicator_weight' => 8,
                'sort_order' => 1,
            ],
            [
                'code' => 'M2',
                'category' => 'Mobilisation & availability',
                'category_weight' => 25,
                'indicator_name' => 'Named operators deployable within 120 minutes for wider regional support',
                'evidence_examples' => 'Roster; availability survey; exercise call-out records',
                'anchor_0' => 'No defined 120-minute support capability',
                'anchor_3' => 'Partial wider-area capability',
                'anchor_5' => 'Named and evidenced operators available for 120-minute support tasks',
                'indicator_weight' => 7,
                'sort_order' => 2,
            ],
            [
                'code' => 'M3',
                'category' => 'Mobilisation & availability',
                'category_weight' => 25,
                'indicator_name' => 'On-call team leader / controller availability',
                'evidence_examples' => 'Duty lead rota; deputy cover; escalation contact chain',
                'anchor_0' => 'No duty lead arrangement',
                'anchor_3' => 'Ad hoc duty lead cover',
                'anchor_5' => 'Reliable duty lead cover with backup',
                'indicator_weight' => 6,
                'sort_order' => 3,
            ],
            [
                'code' => 'M4',
                'category' => 'Mobilisation & availability',
                'category_weight' => 25,
                'indicator_name' => 'Roster visibility for next 28 days and duty contact confidence',
                'evidence_examples' => 'Forward roster; absence tracking; contact validation',
                'anchor_0' => 'No forward visibility',
                'anchor_3' => 'Partial forward visibility',
                'anchor_5' => 'Clear 28-day roster and contact confidence',
                'indicator_weight' => 4,
                'sort_order' => 4,
            ],

            // ── Competence & leadership (weight 15) ──────────────────────────
            [
                'code' => 'C1',
                'category' => 'Competence & leadership',
                'category_weight' => 15,
                'indicator_name' => 'Active members current on core induction',
                'evidence_examples' => 'Training matrix; induction records; membership review',
                'anchor_0' => 'Induction absent or unknown',
                'anchor_3' => 'Most active members inducted',
                'anchor_5' => 'Nearly all active members current and evidenced',
                'indicator_weight' => 3,
                'sort_order' => 5,
            ],
            [
                'code' => 'C2',
                'category' => 'Competence & leadership',
                'category_weight' => 15,
                'indicator_name' => 'Active members current on message handling and logs',
                'evidence_examples' => 'Training records; exercise scripts; assessed performance',
                'anchor_0' => 'Not taught or not current',
                'anchor_3' => 'Usable but patchy currency',
                'anchor_5' => 'Current and evidenced across active operators',
                'indicator_weight' => 3,
                'sort_order' => 6,
            ],
            [
                'code' => 'C3',
                'category' => 'Competence & leadership',
                'category_weight' => 15,
                'indicator_name' => 'Members competent in digital / data modes and bearer bridging',
                'evidence_examples' => 'DMR/YSF/VoIP/LoRa/APRS evidence; task books; network access records',
                'anchor_0' => 'No credible data-mode capability',
                'anchor_3' => 'Limited specialists only',
                'anchor_5' => 'Reliable digital/data capability with depth',
                'indicator_weight' => 3,
                'sort_order' => 7,
            ],
            [
                'code' => 'C4',
                'category' => 'Competence & leadership',
                'category_weight' => 15,
                'indicator_name' => 'Members competent as field team leaders',
                'evidence_examples' => 'Role books; exercise lead records; deployment sign-off',
                'anchor_0' => 'No field leadership depth',
                'anchor_3' => 'One or two likely leaders',
                'anchor_5' => 'Several current leaders with resilience',
                'indicator_weight' => 4,
                'sort_order' => 8,
            ],
            [
                'code' => 'C5',
                'category' => 'Competence & leadership',
                'category_weight' => 15,
                'indicator_name' => 'Competence records current and reviewed',
                'evidence_examples' => 'Training matrix review date; evidence references; expiries tracked',
                'anchor_0' => 'No competence governance',
                'anchor_3' => 'Basic records but not current',
                'anchor_5' => 'Current, reviewable competence record',
                'indicator_weight' => 2,
                'sort_order' => 9,
            ],

            // ── Communications capability (weight 25) ────────────────────────
            [
                'code' => 'CC1',
                'category' => 'Communications capability',
                'category_weight' => 25,
                'indicator_name' => 'Deployable VHF / UHF voice capability',
                'evidence_examples' => 'Serviceable radios; antennas; simplex/repeater plans; test logs',
                'anchor_0' => 'Capability absent or unreliable',
                'anchor_3' => 'Basic voice capability',
                'anchor_5' => 'Robust deployable voice capability',
                'indicator_weight' => 6,
                'sort_order' => 10,
            ],
            [
                'code' => 'CC2',
                'category' => 'Communications capability',
                'category_weight' => 25,
                'indicator_name' => 'Alternative bearers available (DMR / YSF / VoIP / LoRa / data)',
                'evidence_examples' => 'Network diagrams; laptop/router kits; account access; test logs',
                'anchor_0' => 'No alternative bearer',
                'anchor_3' => 'Single fallback only',
                'anchor_5' => 'Multiple tested fallback bearers',
                'indicator_weight' => 5,
                'sort_order' => 11,
            ],
            [
                'code' => 'CC3',
                'category' => 'Communications capability',
                'category_weight' => 25,
                'indicator_name' => 'Formal RAYNET message handling and logging deployable',
                'evidence_examples' => 'RAYNET-UK standard forms; electronic logs; SOPs; training records',
                'anchor_0' => 'No formal system',
                'anchor_3' => 'Basic message/logging only',
                'anchor_5' => 'Repeatable formal handling and logging',
                'indicator_weight' => 5,
                'sort_order' => 12,
            ],
            [
                'code' => 'CC4',
                'category' => 'Communications capability',
                'category_weight' => 25,
                'indicator_name' => 'Tracking / location reporting capability',
                'evidence_examples' => 'APRS or equivalent; device list; live test screenshots',
                'anchor_0' => 'No tracking capability',
                'anchor_3' => 'Limited or experimental',
                'anchor_5' => 'Reliable tracking available when required',
                'indicator_weight' => 3,
                'sort_order' => 13,
            ],
            [
                'code' => 'CC5',
                'category' => 'Communications capability',
                'category_weight' => 25,
                'indicator_name' => 'Communications resilience (spares, antennas, batteries, fallbacks)',
                'evidence_examples' => 'Spare kit list; battery plan; fallback comms plan',
                'anchor_0' => 'Single points of failure dominate',
                'anchor_3' => 'Some redundancy',
                'anchor_5' => 'Well-evidenced redundancy and fallback',
                'indicator_weight' => 6,
                'sort_order' => 14,
            ],

            // ── Sustainment & logistics (weight 10) ──────────────────────────
            [
                'code' => 'S1',
                'category' => 'Sustainment & logistics',
                'category_weight' => 10,
                'indicator_name' => 'Ready-to-go field kits complete',
                'evidence_examples' => 'Kit issue sheets; inspection dates; missing item log',
                'anchor_0' => 'No complete deployment kits',
                'anchor_3' => 'Some kits but inconsistent',
                'anchor_5' => 'Complete field kits ready and checked',
                'indicator_weight' => 2,
                'sort_order' => 15,
            ],
            [
                'code' => 'S2',
                'category' => 'Sustainment & logistics',
                'category_weight' => 10,
                'indicator_name' => 'Independent power endurance',
                'evidence_examples' => 'Battery inventory; power pack test; runtime calculations',
                'anchor_0' => 'Minimal independent power',
                'anchor_3' => 'Can cover short deployments',
                'anchor_5' => 'Credible endurance matched to declared service',
                'indicator_weight' => 2,
                'sort_order' => 16,
            ],
            [
                'code' => 'S3',
                'category' => 'Sustainment & logistics',
                'category_weight' => 10,
                'indicator_name' => 'Vehicle / transport capacity for local deployment',
                'evidence_examples' => 'Vehicle availability; loading plan; driver list',
                'anchor_0' => 'No reliable transport model',
                'anchor_3' => 'Limited transport',
                'anchor_5' => 'Reliable transport for declared service',
                'indicator_weight' => 2,
                'sort_order' => 17,
            ],
            [
                'code' => 'S4',
                'category' => 'Sustainment & logistics',
                'category_weight' => 10,
                'indicator_name' => 'Operator welfare / shelter arrangements',
                'evidence_examples' => 'Shelter list; PPE; catering / welfare plan; toilets / relief plan',
                'anchor_0' => 'No welfare plan',
                'anchor_3' => 'Basic welfare only',
                'anchor_5' => 'Practical welfare and shelter arrangements',
                'indicator_weight' => 2,
                'sort_order' => 18,
            ],
            [
                'code' => 'S5',
                'category' => 'Sustainment & logistics',
                'category_weight' => 10,
                'indicator_name' => 'Ability to sustain 12-hour local operations and 24-hour with relief',
                'evidence_examples' => 'Shift plan; relief model; resupply assumptions',
                'anchor_0' => 'Only short-duration operations',
                'anchor_3' => '12-hour workable but fragile',
                'anchor_5' => '12-hour credible and 24-hour manageable with relief',
                'indicator_weight' => 2,
                'sort_order' => 19,
            ],

            // ── Interoperability & procedures (weight 15) ────────────────────
            [
                'code' => 'I1',
                'category' => 'Interoperability & procedures',
                'category_weight' => 15,
                'indicator_name' => 'JESIP awareness / interoperability familiarity',
                'evidence_examples' => 'Training notes; aide memoires; exercise observation',
                'anchor_0' => 'No interoperability framework awareness',
                'anchor_3' => 'Some awareness',
                'anchor_5' => 'Useful operational familiarity',
                'indicator_weight' => 3,
                'sort_order' => 20,
            ],
            [
                'code' => 'I2',
                'category' => 'Interoperability & procedures',
                'category_weight' => 15,
                'indicator_name' => 'RAYNET-UK standard forms and logs used consistently',
                'evidence_examples' => 'Blank forms; logs; audit samples; exercise evidence',
                'anchor_0' => 'No standard use',
                'anchor_3' => 'Some standard use',
                'anchor_5' => 'Consistent use under exercise / incident conditions',
                'indicator_weight' => 3,
                'sort_order' => 21,
            ],
            [
                'code' => 'I3',
                'category' => 'Interoperability & procedures',
                'category_weight' => 15,
                'indicator_name' => 'Incident reporting and escalation procedure',
                'evidence_examples' => 'Call-out SOP; escalation tree; incident activation checklist',
                'anchor_0' => 'No clear procedure',
                'anchor_3' => 'Basic procedure exists',
                'anchor_5' => 'Clear and practised escalation procedure',
                'indicator_weight' => 3,
                'sort_order' => 22,
            ],
            [
                'code' => 'I4',
                'category' => 'Interoperability & procedures',
                'category_weight' => 15,
                'indicator_name' => 'Information governance / data handling',
                'evidence_examples' => 'Data handling note; retention rules; access control',
                'anchor_0' => 'No data handling discipline',
                'anchor_3' => 'Basic awareness only',
                'anchor_5' => 'Proportionate and evidenced data handling',
                'indicator_weight' => 2,
                'sort_order' => 23,
            ],
            [
                'code' => 'I5',
                'category' => 'Interoperability & procedures',
                'category_weight' => 15,
                'indicator_name' => 'Ability to integrate with local authority / rest centre / RV / field comms cell',
                'evidence_examples' => 'Role cards; setup checklist; partner exercise evidence',
                'anchor_0' => 'Integration not defined',
                'anchor_3' => 'Can probably integrate',
                'anchor_5' => 'Integration capability evidenced',
                'indicator_weight' => 4,
                'sort_order' => 24,
            ],

            // ── Exercising, assurance & improvement (weight 10) ──────────────
            [
                'code' => 'E1',
                'category' => 'Exercising, assurance & improvement',
                'category_weight' => 10,
                'indicator_name' => 'Exercise or structured training frequency in the last 12 months',
                'evidence_examples' => 'Exercise log; attendance sheets; objectives achieved',
                'anchor_0' => 'No meaningful exercising',
                'anchor_3' => 'Occasional training/exercises',
                'anchor_5' => 'Regular and relevant training/exercising',
                'indicator_weight' => 2,
                'sort_order' => 25,
            ],
            [
                'code' => 'E2',
                'category' => 'Exercising, assurance & improvement',
                'category_weight' => 10,
                'indicator_name' => 'Equipment test / maintenance records',
                'evidence_examples' => 'Maintenance sheets; serialised asset records; test schedule',
                'anchor_0' => 'No usable maintenance record',
                'anchor_3' => 'Basic records',
                'anchor_5' => 'Current and disciplined test record',
                'indicator_weight' => 2,
                'sort_order' => 26,
            ],
            [
                'code' => 'E3',
                'category' => 'Exercising, assurance & improvement',
                'category_weight' => 10,
                'indicator_name' => 'Post-exercise or post-task debrief capture',
                'evidence_examples' => 'Debrief notes; hot debrief; lessons log',
                'anchor_0' => 'Lessons not captured',
                'anchor_3' => 'Lessons captured inconsistently',
                'anchor_5' => 'Lessons routinely captured',
                'indicator_weight' => 2,
                'sort_order' => 27,
            ],
            [
                'code' => 'E4',
                'category' => 'Exercising, assurance & improvement',
                'category_weight' => 10,
                'indicator_name' => 'Corrective actions tracked to closure',
                'evidence_examples' => 'Action log; owners; due dates; closed dates',
                'anchor_0' => 'Actions not tracked',
                'anchor_3' => 'Some tracking',
                'anchor_5' => 'Disciplined corrective action closure',
                'indicator_weight' => 2,
                'sort_order' => 28,
            ],
            [
                'code' => 'E5',
                'category' => 'Exercising, assurance & improvement',
                'category_weight' => 10,
                'indicator_name' => 'Capability demonstrated with a local partner or public-service user',
                'evidence_examples' => 'Exercise invite; partner feedback; joint deployment evidence',
                'anchor_0' => 'Internal activity only',
                'anchor_3' => 'Some partner interaction',
                'anchor_5' => 'Capability externally demonstrated and evidenced',
                'indicator_weight' => 2,
                'sort_order' => 29,
            ],
        ];

        foreach ($indicators as $indicator) {
            DB::table('readiness_indicators')->insert(array_merge($indicator, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        // Seed default service levels from the spreadsheet
        $serviceLevels = [
            ['key' => 'organisation_name',      'value' => 'Your RAYNET Group', 'notes' => null],
            ['key' => 'operating_area',         'value' => 'Local group footprint; wider regional support by arrangement', 'notes' => null],
            ['key' => 'operators_60min',        'value' => '4', 'notes' => 'Use numbers you can evidence by named operators inside your group footprint.'],
            ['key' => 'operators_120min',       'value' => '8', 'notes' => null],
            ['key' => 'oncall_team_leader',     'value' => 'Yes', 'notes' => null],
            ['key' => 'voice_modes',            'value' => 'VHF/UHF voice', 'notes' => null],
            ['key' => 'alternative_bearers',    'value' => 'DMR, YSF, VoIP, LoRa, APRS/location reporting', 'notes' => 'List only current, maintained fallback bearers you can evidence.'],
            ['key' => 'endurance_hours',        'value' => '12', 'notes' => 'Match endurance to power, relief, and welfare assumptions.'],
            ['key' => 'sustain_24hr',           'value' => 'Possible with relief/support', 'notes' => null],
            ['key' => 'geographic_limits',      'value' => 'Best suited to local tasks; wider regional support depends on transport, staffing, and task profile', 'notes' => null],
            ['key' => 'key_caveats',            'value' => 'Volunteer turnout; safety; power/internet conditions; vehicle availability; task clarity', 'notes' => 'State the boundaries plainly. Honest caveats increase credibility.'],
        ];

        foreach ($serviceLevels as $sl) {
            DB::table('committee_service_levels')->insertOrIgnore(array_merge($sl, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}