<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 10px; color: #1e293b; background: #fff; }
.header { background: #003366; color: #fff; padding: 14px 20px; display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; }
.header h1 { font-size: 16px; font-weight: 900; letter-spacing: .03em; }
.header .meta { font-size: 9px; color: rgba(255,255,255,.7); margin-top: 3px; }
.badge { display: inline-block; padding: 2px 7px; border-radius: 999px; font-size: 8px; font-weight: 800; }
.badge-full { background: #dcfce7; color: #15803d; }
.badge-found { background: #dbeafe; color: #1d4ed8; }
.badge-registered { background: #fef9c3; color: #a16207; }
table { width: 100%; border-collapse: collapse; }
thead tr { background: #003366; color: #fff; }
thead th { padding: 8px 10px; text-align: left; font-size: 9px; font-weight: 800; letter-spacing: .06em; text-transform: uppercase; }
tbody tr:nth-child(even) { background: #f8fafc; }
tbody tr { border-bottom: 1px solid #e2e8f0; }
td { padding: 7px 10px; vertical-align: middle; }
.cs { font-family: monospace; font-weight: 900; font-size: 11px; color: #003366; }
.name { font-weight: 700; color: #1e293b; }
.muted { color: #94a3b8; font-size: 9px; }
.sig { font-family: monospace; font-weight: 800; color: #059669; }
.footer { margin-top: 16px; font-size: 8px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 8px; }
.reg-yes { color: #15803d; font-weight: 800; }
.reg-no { color: #94a3b8; }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="header h1">{{ $groupName }} — Station Log</div>
    <div class="meta">Net: {{ $netName }} &nbsp;·&nbsp; Exported: {{ $date }} &nbsp;·&nbsp; {{ $stations->count() }} station{{ $stations->count() !== 1 ? 's' : '' }} logged</div>
  </div>
</div>
<table>
  <thead>
    <tr>
      <th style="width:28px;">#</th>
      <th style="width:70px;">Time</th>
      <th style="width:80px;">Callsign</th>
      <th>Name</th>
      <th style="width:70px;">Licence</th>
      <th style="width:110px;">Location</th>
      <th style="width:45px;">Grid</th>
      <th style="width:40px;">Signal</th>
      <th>Notes</th>
      <th style="width:60px;">Member</th>
    </tr>
  </thead>
  <tbody>
  @foreach($stations as $i => $s)
    @php $qrz = is_array($s->qrz_data) ? $s->qrz_data : (json_decode($s->qrz_data ?? '{}', true) ?? []); @endphp
    <tr>
      <td class="muted" style="text-align:center;">{{ $i+1 }}</td>
      <td class="muted">{{ $s->checked_in_at->format('H:i') }}</td>
      <td class="cs">{{ $s->callsign }}</td>
      <td><span class="name">{{ $s->name ?? '—' }}</span></td>
      <td>
        @if(!empty($qrz['licence_class']))
          <span class="badge badge-full">{{ $qrz['licence_class'] }}</span>
        @else —
        @endif
      </td>
      <td class="muted">{{ $qrz['location'] ?? '—' }}</td>
      <td class="muted" style="font-family:monospace;">{{ $qrz['grid'] ?? '—' }}</td>
      <td class="sig">{{ $s->signal_report ?? '—' }}</td>
      <td class="muted">{{ $s->notes ?? '' }}</td>
      <td style="text-align:center;">
        @if($s->is_registered)
          <span class="reg-yes">✓</span>
        @else
          <span class="reg-no">—</span>
        @endif
      </td>
    </tr>
  @endforeach
  </tbody>
</table>
<div class="footer">{{ $groupName }} · Generated by RAYNET-CMS · {{ $date }}</div>
</body>
</html>
